# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: gigabytedevelopers
custom: ['https://github.com/sponsors/gigabytedevlopers', 'https://www.blockchain.com/btc/address/38o3eojc9uSNoJC85YhZZuHvBzAFQ1JDPX', 'https://www.blockchain.com/eth/address/0xDF3aC1cd8f15410705B79004F4fD87509a98CaC6', 'https://www.buymeacoffee.com/gigabytedevs']

